let cards = {
    level0: [
        {name: "Tobbycat",
        attack: 1,
        defence: 1,
        ability: "",
        picture: 'url(https://i.imgur.com/VlqJyBw.png)',
        pictureAlt: "url(./img/tabbycat.png)",
        canSummon: false,
        hasShield: false,
        deathrattle: false,},
    ],
    level1: [
        {name: "Alleycat",
        attack: 1,
        defence: 1,
        ability: "Summon 1/1 Tabbycat",
        picture: 'url(https://i.imgur.com/NA6dbE6.png)',
        pictureAlt: "url(./img/alleycat.png)",
        canSummon: true,
        hasShield: false,
        deathrattle: false,},

        {name: "Dragonspawn",
        attack: 2,
        defence: 3,
        ability: "Taunt",
        picture: 'url(https://i.imgur.com/FKnXZNQ.png)',
        pictureAlt: "url(./img/dragonspawn-lieutenant.png)",
        canSummon: false,
        hasShield: false,
        deathrattle: false,
        taunt: true,
        },
        {
        name: "Righteous Protector",
        attack: 1,
        defence: 1,
        ability: "Divine shield",
        picture: 'url(https://i.imgur.com/2EUdR4x.png)',
        pictureAlt: "url(./img/righteuos-protector.png)",
        canSummon: false,
        hasShield: true,
        deathrattle: false,
        },

        {
        name: "Selfless hero",
        attack: 2,
        defence: 1,
        ability: "On Death gives random friendly card Shield",
        picture: 'url(https://i.imgur.com/4Q23Z9J.png)',
        pictureAlt: "url(./img/selfless-hero.png)",
        deathrattle: true,
        canSummon: false,
        hasShield: false,
        },
        {name: "Unstable Ghoul",
        attack: 1,
        defence: 3,
        ability: "On Death Deals 1 Damage to all Cards. Taunt",
        picture: 'url(https://i.imgur.com/NA6dbE6.png)',
        pictureAlt: "url(./img/unstable-ghoul.png)",
        canSummon: false,
        hasShield: false,
        deathrattle: false,
        taunt: true,
        deal1DmgAll: true
        },
        {name: "spawn-of-nzoth",
        attack: 2,
        defence: 2,
        ability: "On Death gives +1/+1 to all Friendly Cards",
        picture: 'url(https://i.imgur.com/NA6dbE6.png)',
        pictureAlt: "url(./img/spawn-of-nzoth.png)",
        canSummon: false,
        hasShield: false,
        deathrattle: true
        }

    ],
    level2: [
        {name: "Unstable Ghoul",
        attack: 1,
        defence: 3,
        ability: "On Death Deals 1 Damage to all Cards",
        picture: 'url(https://i.imgur.com/NA6dbE6.png)',
        pictureAlt: "url(./img/unstable-ghoul.png)",
        canSummon: false,
        hasShield: false,
        deathrattle: true
        },
        {name: "spawn-of-nzoth",
        attack: 2,
        defence: 2,
        ability: "On Death gives +1/+1 to all Friendly Cards",
        picture: 'url(https://i.imgur.com/NA6dbE6.png)',
        pictureAlt: "url(./img/spawn-of-nzoth.png)",
        canSummon: false,
        hasShield: false,
        deathrattle: true
        }],
    tokens: [
        {name: "Tobbycat",
        attack: 1,
        defence: 1,
        picture: 'url(https://i.imgur.com/VlqJyBw.png)',
        pictureAlt: "url(./img/tabbycat.png)",
        ability: ""},
        
        {name: "dust-devil",
        attack: 2,
        defence: 2,
        picture: 'url(https://i.imgur.com/9J9WXlB.png)',
        pictureAlt: "url(./img/dust-devil.png)",
        ability: ""},

        {name: "windswept-elemntal",
        attack: 4,
        defence: 4  ,
        picture: 'url(https://i.imgur.com/LbY8DzV.png)',
        pictureAlt: "url(./img/windswept-elemntal.png)",
        ability: ""},

        {name: "living-storm",
        attack: 8,
        defence: 8,
        picture: 'url(https://i.imgur.com/FNjZ9gP.png)',
        pictureAlt: "url(./img/living-storm.png)",
        ability: ""},
    ]
}

export default cards